# BACKGROUND
background {
    monitor = 
    path = screenshot
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 3 # 0 disables blurring
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

# NICKNAME
label {
    monitor = 
    text = Exfiltrix
    color = rgba(200, 200, 200, 1.0)
    font_size = 64
    font_family = JetBrains Mono
    position = 0, 80
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor = 
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}

# BOTTOM TEXT
label {
    monitor = 
    text = Do not disturb, code in progress...
    color = rgba(200, 200, 200, 0.6)
    font_size = 18
    font_family = JetBrains Mono
    position = 0, 50
    halign = center
    valign = bottom
}

# TIME (Optional but nice)
label {
    monitor = 
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 20
    font_family = JetBrains Mono
    position = -50, 50
    halign = right
    valign = bottom
}
